runtime: java
env: standard

handlers:
  - url: /.*
    script: this field is required, but ignored
    static_dir: static

instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5

env_variables:
  SPRING_DATASOURCE_URL: jdbc:mysql://google/project-jh-db?cloudSqlInstance=project-jh-425111:europe-west1:project-jh&socketFactory=com.google.cloud.sql.mysql.SocketFactory&useSSL=false
  SPRING_DATASOURCE_USERNAME: root
  SPRING_DATASOURCE_PASSWORD: root

beta_settings:
  cloud_sql_instances: project-jh-425111:europe-west1:project-jh=tcp:3306

spring:
  ai:
    openai:
      model: gpt-3.5-turbo # Model do generowania tekstu
      apiKey: "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"  # Twój klucz API od OpenAI
